package br.com.abastecimentofrota.ui;

import br.com.abastecimentofrota.DTO.LinhaRelatorioCupomDTO;
import br.com.abastecimentofrota.renderer.TotalRowRenderer;
import br.com.abastecimentofrota.service.AbastecimentoService;
import br.com.abastecimentofrota.service.PostoService;
import br.com.abastecimentofrota.service.RelatorioAbastecimentoService;
import br.com.abastecimentofrota.service.VeiculoService;
import br.com.abastecimentofrota.util.RelatorioCuponsTableModel;
import br.com.abastecimentofrota.util.TipoCombustivel;
import br.com.abastecimentofrota.util.TipoCombustivelComboBoxModel;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Administração01
 */
public class TelaRelatorioAbastecimento extends javax.swing.JFrame {

    //valores combobox Mes
    String[] meses = {
        "01 - Janeiro", "02 - Fevereiro", "03 - Março", "04 - Abril",
        "05 - Maio", "06 - Junho", "07 - Julho", "08 - Agosto",
        "09 - Setembro", "10 - Outubro", "11 - Novembro", "12 - Dezembro"
    };

    //valor combobox ano
    String[] anos = {
        "2025"
    };

    //variaveis do Srping
    private final VeiculoService veiculoService;
    private final AbastecimentoService abastecimentoService;
    private final PostoService postoService;
    private final RelatorioAbastecimentoService relatorioService;

    public TelaRelatorioAbastecimento(VeiculoService veiculoService, AbastecimentoService abastecimentoService, PostoService postoService, RelatorioAbastecimentoService relatorioService) {
        this.veiculoService = veiculoService;
        this.abastecimentoService = abastecimentoService;
        this.postoService = postoService;
        this.relatorioService = relatorioService;

        initComponents();

        //configurando os combobox
        TipoCombustivelComboBoxModel comboTipoCombustivel = new TipoCombustivelComboBoxModel();
        comboCombustivel.setModel(comboTipoCombustivel);

        //configurando as tables
        List<LinhaRelatorioCupomDTO> dadosIniciaisPagos = new ArrayList<>();
        RelatorioCuponsTableModel tableModelPagos = new RelatorioCuponsTableModel(dadosIniciaisPagos);
        configurarTabela(tablePagos, tableModelPagos);
        
        List<LinhaRelatorioCupomDTO> dadosIniciaisPagosNaoCadastrados = new ArrayList<>();
        RelatorioCuponsTableModel tableModelPagosNaoCadastrados = new RelatorioCuponsTableModel(dadosIniciaisPagosNaoCadastrados);
        configurarTabela(tablePagosNaoCadastrados, tableModelPagosNaoCadastrados);

        List<LinhaRelatorioCupomDTO> dadosIniciaisNaoPagosNaoCadastrados = new ArrayList<>();
        RelatorioCuponsTableModel tableModelNaoPagosNaoCadastrados = new RelatorioCuponsTableModel(dadosIniciaisNaoPagosNaoCadastrados);
        configurarTabela(tableNaoPagosNaoCadastrados, tableModelNaoPagosNaoCadastrados);

    }

    private void configurarTabela(JTable tabela, RelatorioCuponsTableModel tableModel) {
        tabela.setModel(tableModel);
        tabela.setDefaultRenderer(Object.class, new TotalRowRenderer());
        tabela.setGridColor(Color.LIGHT_GRAY);
        tabela.setFont(new Font("SansSerif", Font.PLAIN, 12));
        tabela.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMes = new javax.swing.JLabel();
        comboMes = new javax.swing.JComboBox<>();
        labelAno = new javax.swing.JLabel();
        labelAno1 = new javax.swing.JLabel();
        comboCombustivel = new javax.swing.JComboBox<>();
        buttonBuscar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePagos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePagosNaoCadastrados = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableNaoPagosNaoCadastrados = new javax.swing.JTable();
        buttonExportar = new javax.swing.JButton();
        comboAno = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Conciliação");

        labelMes.setText("Mês*");

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(meses));

        labelAno.setText("Ano*");

        labelAno1.setText("Combustível*");

        buttonBuscar.setBackground(new java.awt.Color(76, 175, 80));
        buttonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        tablePagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePagos);

        jTabbedPane1.addTab("Pagos", jScrollPane1);

        tablePagosNaoCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablePagosNaoCadastrados);

        jTabbedPane1.addTab("Pagos e não cadastrados", jScrollPane2);

        tableNaoPagosNaoCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableNaoPagosNaoCadastrados);

        jTabbedPane1.addTab("Não pagos e cadastrados", jScrollPane3);

        buttonExportar.setBackground(new java.awt.Color(76, 175, 80));
        buttonExportar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonExportar.setForeground(new java.awt.Color(255, 255, 255));
        buttonExportar.setText("Exportar PDF");
        buttonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportarActionPerformed(evt);
            }
        });

        comboAno.setModel(new javax.swing.DefaultComboBoxModel<>(anos));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboAno, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonExportar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMes)
                    .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAno)
                    .addComponent(labelAno1)
                    .addComponent(comboCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar)
                    .addComponent(comboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExportar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        int mes = comboMes.getSelectedIndex() + 1; // Janeiro = 0
        int ano = Integer.parseInt((String) comboAno.getSelectedItem()); // ou outro ano selecionável
        TipoCombustivel tipoCombustivel = (TipoCombustivel) comboCombustivel.getSelectedItem();

        List<LinhaRelatorioCupomDTO> pagos = relatorioService.buscarCuponsPagosDTO(mes, ano, tipoCombustivel);
        List<LinhaRelatorioCupomDTO> pendentes = relatorioService.buscarCuponsNaoCadastradosDTO(mes, ano, tipoCombustivel);
        List<LinhaRelatorioCupomDTO> semNota = relatorioService.buscarAbastecimentosSemNotaDTO(mes, ano, tipoCombustivel);

        //listas com totais
        List<LinhaRelatorioCupomDTO> pagosComTotal = relatorioService.agruparComTotais(pagos);

        RelatorioCuponsTableModel modelPagos = (RelatorioCuponsTableModel) tablePagos.getModel();
        modelPagos.setDados(pagosComTotal);

        RelatorioCuponsTableModel modelPagosNaoCadastrados = (RelatorioCuponsTableModel) tablePagosNaoCadastrados.getModel();
        modelPagosNaoCadastrados.setDados(pendentes);

        RelatorioCuponsTableModel modelNaoPagosNaoCadastrados = (RelatorioCuponsTableModel) tableNaoPagosNaoCadastrados.getModel();
        modelNaoPagosNaoCadastrados.setDados(semNota);
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExportarActionPerformed
        JOptionPane.showConfirmDialog(rootPane, "Metodo ainda não implementado");
    }//GEN-LAST:event_buttonExportarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonExportar;
    private javax.swing.JComboBox<String> comboAno;
    private javax.swing.JComboBox<TipoCombustivel> comboCombustivel;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelAno1;
    private javax.swing.JLabel labelMes;
    private javax.swing.JTable tableNaoPagosNaoCadastrados;
    private javax.swing.JTable tablePagos;
    private javax.swing.JTable tablePagosNaoCadastrados;
    // End of variables declaration//GEN-END:variables
}
